2025-01-10 22:41:14,724 INFO    MainThread:15295 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-01-10 22:41:14,725 INFO    MainThread:15295 [wandb_setup.py:_flush():68] Configure stats pid to 15295
2025-01-10 22:41:14,725 INFO    MainThread:15295 [wandb_setup.py:_flush():68] Loading settings from /home/kunalkushwahatg/.config/wandb/settings
2025-01-10 22:41:14,725 INFO    MainThread:15295 [wandb_setup.py:_flush():68] Loading settings from /home/kunalkushwahatg/Research/wandb/settings
2025-01-10 22:41:14,725 INFO    MainThread:15295 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-10 22:41:14,725 INFO    MainThread:15295 [wandb_init.py:_log_setup():523] Logging user logs to /home/kunalkushwahatg/Research/wandb/run-20250110_224114-cqey7g8g/logs/debug.log
2025-01-10 22:41:14,726 INFO    MainThread:15295 [wandb_init.py:_log_setup():524] Logging internal logs to /home/kunalkushwahatg/Research/wandb/run-20250110_224114-cqey7g8g/logs/debug-internal.log
2025-01-10 22:41:14,726 INFO    MainThread:15295 [wandb_init.py:init():641] calling init triggers
2025-01-10 22:41:14,726 INFO    MainThread:15295 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {}
2025-01-10 22:41:14,726 INFO    MainThread:15295 [wandb_init.py:init():674] starting backend
2025-01-10 22:41:16,390 WARNING MainThread:15295 [wandb_init.py:init():1293] interrupted
Traceback (most recent call last):
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 677, in init
    service = self._wl.ensure_service()
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 280, in ensure_service
    self._connection = service_connection.connect_to_service(self._settings)
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 40, in connect_to_service
    return _start_and_connect_service(settings)
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 75, in _start_and_connect_service
    proc.start()
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 232, in start
    self._launch_server()
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 224, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/home/kunalkushwahatg/anaconda3/envs/research/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 105, in _wait_for_ports
    time.sleep(0.2)
KeyboardInterrupt
